services:
  computing-core:
    build: 
      context: ${PROJECT_ROOT}/computing-core
      dockerfile: /cmd/app/Dockerfile
    container_name: computing-core-app
    env_file:
      - ${PROJECT_ROOT}/computing-core/.env
    environment:
      - LOGGER_FOLDER=${PROJECT_ROOT}/computing-core/out/logs
    volumes:
      - ${PROJECT_ROOT}/computing-core/out/logs:/app/out/logs
    ports:
      - "8001:8001"

  gateway:
    build: 
      context: ${PROJECT_ROOT}/gateway
      dockerfile: /cmd/app/Dockerfile
    container_name: gateway-app
    env_file:
      - ${PROJECT_ROOT}/gateway/.env
    environment:
      - LOGGER_FOLDER=${PROJECT_ROOT}/gateway/out/logs
    volumes:
      - ${PROJECT_ROOT}/gateway/out/logs:/app/out/logs
    ports:
      - "8000:8000"
  