// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/google/wire"
	"github.com/markgredasov/rest-calculator-service/internal/core/logger"
	"github.com/markgredasov/rest-calculator-service/internal/core/transport/http/middleware"
	"github.com/markgredasov/rest-calculator-service/internal/core/transport/http/server"
	"github.com/markgredasov/rest-calculator-service/internal/features/calculator/service"
	"github.com/markgredasov/rest-calculator-service/internal/features/calculator/transport/http"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*App, error) {
	config := core_logger.NewConfigMust()
	logger, err := core_logger.NewLogger(config)
	if err != nil {
		return nil, err
	}
	core_http_serverConfig := core_http_server.NewConfigMust()
	v := provideMiddlewares(logger)
	calculatorHTTPHandler := provideCalculatorHandler()
	apiVersionRouter := provideAPIRouter(calculatorHTTPHandler)
	httpServer := provideServer(core_http_serverConfig, logger, v, apiVersionRouter)
	app := NewApp(logger, httpServer)
	return app, nil
}

// wire.go:

var ProviderSet = wire.NewSet(core_logger.NewConfigMust, core_logger.NewLogger, provideCalculatorHandler,
	provideAPIRouter, core_http_server.NewConfigMust, provideMiddlewares,
	provideServer,

	NewApp,
)

func provideCalculatorHandler() *calculator_transport.CalculatorHTTPHandler {
	calculatorService := calculator_service.NewCalculatorService(nil)
	calculatorHTTPHandler := calculator_transport.NewCalculatorHTTPHandler(&calculatorService)

	return calculatorHTTPHandler
}

func provideAPIRouter(
	calculatorHTTPHandler *calculator_transport.CalculatorHTTPHandler,
) *core_http_server.APIVersionRouter {
	apiInternalRouter := core_http_server.NewApiVersionRouter(core_http_server.ApiPrefixInternal)
	apiInternalRouter.RegisterRoutes(calculatorHTTPHandler.Routes()...)

	return apiInternalRouter
}

func provideMiddlewares(
	logger *core_logger.Logger,
) []core_http_middleware.Middleware {
	return []core_http_middleware.Middleware{core_http_middleware.CORS(), core_http_middleware.RequestID(), core_http_middleware.Logger(logger), core_http_middleware.Recovery(), core_http_middleware.Trace()}
}

func provideServer(
	config core_http_server.Config,
	logger *core_logger.Logger,
	middlewares []core_http_middleware.Middleware,
	router *core_http_server.APIVersionRouter,
) *core_http_server.HTTPServer {
	server := core_http_server.NewHTTPServer(config, logger, middlewares...)
	server.RegisterAPIRouters(router)

	return server
}
